# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2bf9d945639543b21329fc126ddb4de8d79de7cca8e25c716929a426fb8f2a7a0f13ca90a91e681dd1f1a1302d72882a693fdffd7bf130797ac1e73383d9413d

test:
  secret_key_base: 2fdeed55e1fa89a0473e564fdc642ef15c7c8633828b03607df5efe1b5b2b2b6a426cd40f72e0b94fdc99f86405e39c2f49506be423e9cfef4f54667e177dce2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
